import { beforeEach, describe, expect, it, vi } from 'vitest';
import * as coverageService from '../../backend/coverage-service.js';
import { resetData } from '../../backend/data.js';
import { computeBindingHash, type ActionEnvelope } from '../../shared/action-envelope.js';
import type { ApprovalStore, ApprovalStoreState, AuditEvent, ExecutionClaim, PendingAction, Receipt } from '../../shared/approval-store.js';
import { actors } from '../../shared/authorization.js';
import type { ExecutionDependencies } from './agent.js';
import { executeApproved } from './agent.js';

const envelope = (overrides: Partial<ActionEnvelope> = {}): ActionEnvelope => ({ schemaVersion: '1', actionId: 'action-5', tenantId: 'tenant-northstar', actorId: 'csr-7', toolName: 'proposeCoverageChange', action: { type: 'coverage.change', input: { memberId: 'member-ada', targetStatus: 'inactive' } }, preview: { summary: 'Set Ada inactive', changes: [{ field: 'coverageStatus', before: 'active', after: 'inactive' }] }, recordRevision: 1, risk: 'high', createdAt: '2026-01-01T00:00:00.000Z', expiresAt: '2099-01-01T00:00:00.000Z', idempotencyKey: 'coverage-5', ...overrides });

class WorkflowStore implements ApprovalStore {
  actions = new Map<string, PendingAction>(); receipts = new Map<string, Receipt>(); audits: AuditEvent[] = []; claims = new Map<string, Promise<Receipt>>(); resolveClaims = new Map<string, (receipt: Receipt) => void>();
  async create(value: ActionEnvelope) { const pending = structuredClone({ ...value, state: 'proposed' as const, bindingHash: computeBindingHash(value) }); this.actions.set(value.actionId, pending); await this.appendAudit({ actionId: value.actionId, event: 'proposed', at: new Date().toISOString(), actorId: value.actorId }); return structuredClone(pending); }
  async get(id: string) { const value = this.actions.get(id); return value && structuredClone(value); }
  async save(value: PendingAction) { this.actions.set(value.actionId, structuredClone(value)); }
  async approve(id: string, approverId: string) { const value = this.actions.get(id)!; value.state = 'approved'; value.approvedBy = approverId; value.approvedAt = new Date().toISOString(); await this.appendAudit({ actionId: id, event: 'approved', at: value.approvedAt, actorId: approverId }); return structuredClone(value); }
  async reject(id: string, rejectorId: string, reason: string) { const value = this.actions.get(id)!; value.state = 'rejected'; value.rejectedBy = rejectorId; value.rejectedAt = new Date().toISOString(); value.reason = reason; await this.appendAudit({ actionId: id, event: 'rejected', at: value.rejectedAt, actorId: rejectorId, reason }); return structuredClone(value); }
  async listPending(tenantId: string): Promise<PendingAction[]> { return [...this.actions.values()].filter(action => action.tenantId === tenantId && action.state === 'proposed').map(action => structuredClone(action)); }
  async getReceipt(key: string) { const value = this.receipts.get(key); return value && structuredClone(value); }
  async saveReceipt(key: string, receipt: Receipt) { this.receipts.set(key, structuredClone(receipt)); this.resolveClaims.get(key)?.(structuredClone(receipt)); }
  async claimExecution(key: string): Promise<ExecutionClaim> { const receipt = await this.getReceipt(key); if (receipt) return { claimed: false, existingReceipt: receipt }; const priorClaim = this.claims.get(key); if (priorClaim) return { claimed: false, existingReceipt: await priorClaim }; let resolve!: (receipt: Receipt) => void; const winner = new Promise<Receipt>(result => { resolve = result; }); this.claims.set(key, winner); this.resolveClaims.set(key, resolve); return { claimed: true }; }
  async appendAudit(event: AuditEvent) { this.audits.push(structuredClone(event)); }
  async listAudit(actionId: string): Promise<AuditEvent[]> { return this.audits.filter(event => event.actionId === actionId).map(event => structuredClone(event)); }
  async exportState(): Promise<ApprovalStoreState> { return { actions: [...this.actions.values()].map(action => structuredClone(action) as PendingAction), receipts: [...this.receipts.entries()].map(entry => structuredClone(entry) as [string, Receipt]), audits: this.audits.map(event => structuredClone(event) as AuditEvent) }; }
  async restoreState(state: ApprovalStoreState): Promise<void> { this.actions = new Map(state.actions.map(action => [action.actionId, structuredClone(action)])); this.receipts = new Map(state.receipts.map(([key, receipt]) => [key, structuredClone(receipt)])); this.audits = state.audits.map(event => structuredClone(event) as AuditEvent); }
}
function dependencies(store: ApprovalStore, actor = 'csr-7'): ExecutionDependencies { return { store, actor }; }
async function approved(store = new WorkflowStore(), overrides: Partial<ActionEnvelope> = {}) { const value = envelope(overrides); await store.create(value); await store.approve(value.actionId, 'reviewer-1'); return { store, value }; }
beforeEach(() => { resetData(); vi.restoreAllMocks(); });

describe('Stage 05 exercise', () => {
  it.each(['proposed', 'rejected', 'expired', 'executed', 'failed'] as const)('refuses a %s action without mutating the backend', async state => { const store = new WorkflowStore(); const value = envelope(); await store.create(value); const pending = (await store.get(value.actionId))!; pending.state = state; await store.save(pending); const execute = vi.spyOn(coverageService, 'updateCoverage'); await expect(executeApproved(value.actionId, dependencies(store))).rejects.toThrow(new RegExp(state)); expect(execute).not.toHaveBeenCalled(); });
  it('handles a missing action id explicitly', async () => { await expect(executeApproved('missing-action', dependencies(new WorkflowStore()))).rejects.toThrow(/missing|not found|unknown/i); });
  it('refuses an envelope that fails ActionEnvelopeSchema when execution resumes', async () => { const { store, value } = await approved(); const malformed: { recordRevision: unknown } = (await store.get(value.actionId))!; malformed.recordRevision = 'one'; await store.save(malformed as unknown as PendingAction); await expect(executeApproved(value.actionId, dependencies(store))).rejects.toThrow(/schema|invalid|recordRevision/i); });
  it.each([
    ['action input', (pending: PendingAction) => { pending.action.input.targetStatus = 'active'; }],
    ['structured preview', (pending: PendingAction) => { pending.preview.changes[0].after = 'active'; }],
    ['record revision', (pending: PendingAction) => { pending.recordRevision = 2; }],
  ] as const)('rejects a tampered stored %s before any backend call and audits the integrity failure', async (_field, tamper) => { const { store, value } = await approved(); const pending = (await store.get(value.actionId))!; tamper(pending); await store.save(pending); const lookup = vi.spyOn(coverageService, 'lookupCoverage'); const execute = vi.spyOn(coverageService, 'updateCoverage'); await expect(executeApproved(value.actionId, dependencies(store))).rejects.toThrow(/binding|integrity|tamper/i); expect(lookup).not.toHaveBeenCalled(); expect(execute).not.toHaveBeenCalled(); expect(await store.get(value.actionId)).toMatchObject({ state: 'failed' }); expect(await store.listAudit(value.actionId)).toContainEqual(expect.objectContaining({ event: 'failed', reason: expect.stringMatching(/binding|integrity|tamper/i) })); });
  it('re-runs authorization and reports missing-permission after it is revoked', async () => { const { store, value } = await approved(); const actor = actors.find(candidate => candidate.id === 'csr-7')!; const original = [...actor.permissions]; actor.permissions = []; try { await expect(executeApproved(value.actionId, dependencies(store))).rejects.toThrow(/missing-permission/i); } finally { actor.permissions = original; } });
  it('detects real record revision drift without a stale backend write, marks the action failed, and audits it', async () => { const { store, value } = await approved(); await coverageService.updateCoverage('member-ada', 'inactive', 1); const recordBeforeExecution = await coverageService.lookupCoverage('member-ada'); const execute = vi.spyOn(coverageService, 'updateCoverage'); await expect(executeApproved(value.actionId, dependencies(store))).rejects.toThrow(/drift|revision/i); expect(execute).not.toHaveBeenCalled(); expect(await coverageService.lookupCoverage('member-ada')).toEqual(recordBeforeExecution); expect(await store.get(value.actionId)).toMatchObject({ state: 'failed' }); expect(await store.listAudit(value.actionId)).toContainEqual(expect.objectContaining({ event: 'failed' })); });
  it('returns an existing receipt before making any backend calls', async () => { const { store, value } = await approved(); const receipt: Receipt = { actionId: value.actionId, tenantId: value.tenantId, executedAt: '2026-01-01T01:00:00.000Z', toolName: 'proposeCoverageChange', bindingHash: computeBindingHash(value), outcome: 'success' }; await store.saveReceipt(value.idempotencyKey, receipt); const lookup = vi.spyOn(coverageService, 'lookupCoverage'); const execute = vi.spyOn(coverageService, 'updateCoverage'); await expect(executeApproved(value.actionId, dependencies(store))).resolves.toEqual(receipt); expect(lookup).not.toHaveBeenCalled(); expect(execute).not.toHaveBeenCalled(); });
  it('executes once and returns an identical receipt on retry', async () => { const { store, value } = await approved(); const execute = vi.spyOn(coverageService, 'updateCoverage'); const first = await executeApproved(value.actionId, dependencies(store)); const second = await executeApproved(value.actionId, dependencies(store)); expect(execute).toHaveBeenCalledTimes(1); expect(second).toEqual(first); });
  it('coordinates independent executors sharing a durable store into one mutation and one receipt', async () => { const { store, value } = await approved(); const execute = vi.spyOn(coverageService, 'updateCoverage'); const firstExecutor = dependencies(store); const secondExecutor = dependencies(store); const [first, second] = await Promise.all([executeApproved(value.actionId, firstExecutor), executeApproved(value.actionId, secondExecutor)]); expect(execute).toHaveBeenCalledTimes(1); expect(second).toEqual(first); expect(await store.getReceipt(value.idempotencyKey)).toEqual(first); });
  it('returns the winning receipt when separate executor call sites contend for the same idempotency key', async () => { const { store, value } = await approved(); const execute = vi.spyOn(coverageService, 'updateCoverage'); const fromJobWorker = executeApproved(value.actionId, dependencies(store)); const fromResumeHandler = executeApproved(value.actionId, dependencies(store)); const [jobReceipt, resumedReceipt] = await Promise.all([fromJobWorker, fromResumeHandler]); expect(execute).toHaveBeenCalledTimes(1); expect(resumedReceipt).toEqual(jobReceipt); expect(await store.getReceipt(value.idempotencyKey)).toEqual(jobReceipt); });
  it('persists executed state and a receipt keyed by idempotency key with the approved binding hash', async () => { const { store, value } = await approved(); const receipt = await executeApproved(value.actionId, dependencies(store)); expect(await store.get(value.actionId)).toMatchObject({ state: 'executed' }); expect(await store.getReceipt(value.idempotencyKey)).toEqual(receipt); expect(receipt).toMatchObject({ bindingHash: computeBindingHash(value), outcome: 'success' }); });
  it('marks backend failures failed, audits them, and persists only a failure receipt', async () => { const { store, value } = await approved(); vi.spyOn(coverageService, 'updateCoverage').mockRejectedValueOnce(new Error('backend unavailable')); await expect(executeApproved(value.actionId, dependencies(store))).rejects.toThrow(/backend unavailable/i); expect(await store.get(value.actionId)).toMatchObject({ state: 'failed' }); expect(await store.listAudit(value.actionId)).toContainEqual(expect.objectContaining({ event: 'failed' })); expect(await store.getReceipt(value.idempotencyKey)).toMatchObject({ outcome: 'failure', error: expect.stringMatching(/backend unavailable/i) }); });
  it('records workflow-produced proposed, approved, and executed audit events in timestamp order', async () => { const { store, value } = await approved(); await executeApproved(value.actionId, dependencies(store)); const audit = await store.listAudit(value.actionId); expect(audit.map(event => event.event)).toEqual(['proposed', 'approved', 'executed']); expect(audit.map(event => event.at)).toEqual([...audit.map(event => event.at)].sort()); });
});
