import { describe, expect, it } from 'vitest';
import { computeBindingHash, type ActionEnvelope } from '../../shared/action-envelope.js';
import type { ApprovalStore } from '../../shared/approval-store.js';
import { InMemoryApprovalStore, decide, requestApproval, verifyBinding } from './agent.js';

const envelope = (overrides: Partial<ActionEnvelope> = {}): ActionEnvelope => ({ schemaVersion: '1', actionId: 'action-4', tenantId: 'tenant-northstar', actorId: 'csr-7', toolName: 'proposeCoverageChange', action: { type: 'coverage.change', input: { memberId: 'member-ada', targetStatus: 'inactive' } }, preview: { summary: 'Set Ada coverage inactive', changes: [{ field: 'coverageStatus', before: 'active', after: 'inactive' }] }, recordRevision: 1, risk: 'high', createdAt: '2026-01-01T00:00:00.000Z', expiresAt: '2099-01-01T00:00:00.000Z', idempotencyKey: 'coverage-4', ...overrides });

describe('Stage 04 exercise', () => {
  it('does not execute anything when an action is proposed for approval', async () => { const store = new InMemoryApprovalStore(); await requestApproval(store, envelope()); expect(await store.get('action-4')).toMatchObject({ state: 'proposed' }); });
  it('keeps a pending action retrievable after requestApproval has returned', async () => { const store = new InMemoryApprovalStore(); await requestApproval(store, envelope()); expect(await store.get('action-4')).toBeDefined(); });
  it('survives a restart when an exported persistent snapshot is restored into a fresh store', async () => { const store = new InMemoryApprovalStore(); await requestApproval(store, envelope()); const persistedState = await store.exportState(); const restored = new InMemoryApprovalStore(); await restored.restoreState(persistedState); expect(await restored.get('action-4')).toMatchObject({ state: 'proposed', bindingHash: computeBindingHash(envelope()) }); });
  it('fails approval binding when input is mutated after proposal', async () => { const store = new InMemoryApprovalStore(); await requestApproval(store, envelope()); expect(await verifyBinding(store, 'action-4', { type: 'coverage.change', input: { memberId: 'member-ada', targetStatus: 'active' } })).toBe(false); });
  it('copies an envelope on create so later caller mutation cannot alter its action or binding', async () => { const store = new InMemoryApprovalStore(); const proposed = envelope(); await store.create(proposed); proposed.action.input.targetStatus = 'active'; proposed.preview.changes[0].after = 'active'; expect(await store.get('action-4')).toMatchObject({ action: { input: { targetStatus: 'inactive' } }, preview: { changes: [{ after: 'inactive' }] }, bindingHash: computeBindingHash(envelope()) }); });
  it('canonicalises key order without changing the binding hash', () => { const original = envelope(); const reordered = envelope({ action: { type: 'coverage.change', input: { targetStatus: 'inactive', memberId: 'member-ada' } } }); expect(computeBindingHash(reordered)).toBe(computeBindingHash(original)); });
  it('changes the binding hash when only the structured preview changes', () => { const original = envelope(); const altered = envelope({ preview: { summary: 'Different reviewer-visible effect', changes: original.preview.changes } }); expect(computeBindingHash(altered)).not.toBe(computeBindingHash(original)); });
  it('changes the binding hash when only the record revision changes', () => { const original = envelope(); expect(computeBindingHash(envelope({ recordRevision: 2 }))).not.toBe(computeBindingHash(original)); });
  it('materialises expiry as an expired terminal state rather than only rejecting approval', async () => { const store = new InMemoryApprovalStore(); await requestApproval(store, envelope({ expiresAt: '2020-01-01T00:00:00.000Z' })); await expect(decide(store, 'action-4', 'approved', 'reviewer-1')).rejects.toThrow(/expired/i); expect(await store.get('action-4')).toMatchObject({ state: 'expired' }); });
  it('records an approver, approval timestamp, and approval audit event', async () => { const store = new InMemoryApprovalStore(); await requestApproval(store, envelope()); await decide(store, 'action-4', 'approved', 'reviewer-1'); expect(await store.get('action-4')).toMatchObject({ state: 'approved', approvedBy: 'reviewer-1', approvedAt: expect.any(String) }); expect(await store.listAudit('action-4')).toContainEqual(expect.objectContaining({ event: 'approved', actorId: 'reviewer-1' })); });
  it('records a rejector, timestamp, reason, and rejection audit event', async () => { const store = new InMemoryApprovalStore(); await requestApproval(store, envelope()); await decide(store, 'action-4', 'rejected', 'reviewer-1', 'Member withdrew consent'); expect(await store.get('action-4')).toMatchObject({ state: 'rejected', rejectedBy: 'reviewer-1', rejectedAt: expect.any(String), reason: 'Member withdrew consent' }); expect(await store.listAudit('action-4')).toContainEqual(expect.objectContaining({ event: 'rejected', actorId: 'reviewer-1', reason: 'Member withdrew consent' })); });
  it('refuses a second decision after an action is terminal', async () => { const store = new InMemoryApprovalStore(); await requestApproval(store, envelope()); await decide(store, 'action-4', 'rejected', 'reviewer-1', 'no'); await expect(decide(store, 'action-4', 'approved', 'reviewer-1')).rejects.toThrow(/terminal|already|decided/i); });
  it('refuses an approver from the other seeded tenant', async () => { const store = new InMemoryApprovalStore(); await requestApproval(store, envelope()); await expect(decide(store, 'action-4', 'approved', 'lakeside-reviewer-1')).rejects.toThrow(/tenant/i); });
  it('refuses self-approval by the proposing actor', async () => { const store = new InMemoryApprovalStore(); await requestApproval(store, envelope()); await expect(decide(store, 'action-4', 'approved', 'csr-7')).rejects.toThrow(/self|proposer/i); });
  it('lists only pending actions belonging to the requested tenant', async () => { const store = new InMemoryApprovalStore(); await requestApproval(store, envelope()); await requestApproval(store, envelope({ actionId: 'lakeside-action', tenantId: 'tenant-lakeside', actorId: 'lakeside-csr-1', action: { type: 'coverage.change', input: { memberId: 'member-cora', targetStatus: 'inactive' } } })); expect(await store.listPending('tenant-northstar')).toHaveLength(1); expect(await store.listPending('tenant-lakeside')).toHaveLength(1); });
});
